### ISSUE TITLE
data preprocess

### ISSUE THREAD

**Issue by Miraclerice** [junyuchen245/Registration_Uncertainty#3]
Hello, as far as I know, the data dimensions of each subject in the heart dataset are inconsistent, and the physical spacing is also different. I would like to know how the authors preprocessed these datasets to [160,192,224], resampling to a physical spacing, post-center clipping or zeroing @junyuchen245

**Comment by junyuchen245** [comment]
Hi,

The input dimensions were actually set to 128x128x32, different from what you mentioned, as indicated in the training script for the TransMorph model, which you can see here:

https://github.com/junyuchen245/Registration_Uncertainty/blob/main/TransMorph_Uncert/train_TransMorphTVF.py#L49

The images were specifically cropped around the center of the heart and resampled to have an isotropic voxel size in the x and y dimensions. I might share my preprocessing scripts at a later time.

Junyu

**Comment by Miraclerice** [comment]
Thank you very much for your answer. I will try according to what you said. I hope everything goes well with you
